---
on:
  push:
    branches: master
  pull_request:
    branches: master

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix flake check

  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          nix build

          _os=""
          case "${{ matrix.os }}" in
          "ubuntu-")
            _os="x86_64-linux.tar.gz"
            ;;
          "macos-")
            _os="aarch64-macos.tar.gz"
            ;;
          esac
          echo "_os=${_os}" >> $GITHUB_ENV

          tar czf clg-${_os}.tar.gz ./result/bin/clg ./LICENSE ./README.md

      - uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            clg-${{ env._os }}.tar.gz
            LICENSE
            README.md
