---
name: builds, tests, etc.

on: [push, pull_request]

permissions: read-all

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        # os: [ubuntu-latest, macos-latest]
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix build
      - run: nix flake check
# ---
# name: Builds, tests & co
#
# on:
#   - push
#   - pull_request
#
# permissions: read-all
#
# jobs:
#   build:
#     strategy:
#       fail-fast: false
#       matrix:
#         os:
#           - ubuntu-latest
#           - macos-latest
#           - windows-latest
#
#     runs-on: ${{ matrix.os }}
#
#     steps:
#       - name: Checkout tree
#         uses: actions/checkout@v4
#
#       - name: Set-up OCaml
#         uses: ocaml/setup-ocaml@v3
#         with:
#           ocaml-compiler: 5
#
#       - run: opam install . --deps-only --with-test
#       - run: opam exec -- dune build
#       - run: opam exec -- dune runtest
#       - name: Generate artifact attestation
#         uses: actions/attest-build-provenance@v2
#         with:
#           subject-path: _build/default/main.exe
#
#       - name: Upload the build artifact
#         uses: actions/upload-artifact@v4
#         with:
#           name: clg-${{ matrix.os }}
#           path: _build/default/main.exe
#
#   lint-doc:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout tree
#         uses: actions/checkout@v4
#       - name: Set-up OCaml
#         uses: ocaml/setup-ocaml@v3
#         with:
#           ocaml-compiler: 5
#       - uses: ocaml/setup-ocaml/lint-doc@v3
#
#   lint-fmt:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout tree
#         uses: actions/checkout@v4
#       - name: Set-up OCaml
#         uses: ocaml/setup-ocaml@v3
#         with:
#           ocaml-compiler: 5
#       - uses: ocaml/setup-ocaml/lint-fmt@v3
#
#   lint-opam:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout tree
#         uses: actions/checkout@v4
#       - name: Set-up OCaml
#         uses: ocaml/setup-ocaml@v3
#         with:
#           ocaml-compiler: 5
#       - uses: ocaml/setup-ocaml/lint-opam@v3
